const CartActionTypes = {
	TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
	ADD_ITEM: 'ADD_ITEM',
	DELETE_ITEM: 'DELETE_ITEM',
	REDUCE_QUANTITY_AT_CHECKOUT: 'REDUCE_QUANTITY_AT_CHECKOUT',
	CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;
